/**
 * Caddy Configuration Generator
 * Caddyfile generation with TLS, reverse proxy
 */

/**
 * Generate a Caddyfile configuration
 * @param {Object} options - Caddy configuration options
 * @param {string} options.domain - Domain name
 * @param {string} [options.upstream] - Upstream server address
 * @param {string} [options.email] - Email for TLS certificates
 * @returns {string} Caddyfile configuration
 */
export function generateCaddyfile(options = {}) {
  const { domain, upstream = 'localhost:3000', email } = options;

  const lines = [
    '# Caddyfile Configuration',
    '# Generated by TLC Caddy Config',
    '',
  ];

  // Global options
  lines.push('{');
  if (email) {
    lines.push(`    email ${email}`);
  }
  lines.push('}');
  lines.push('');

  // Site block
  lines.push(`${domain} {`);
  lines.push('    # TLS Configuration');
  lines.push('    tls {');
  lines.push('        protocols tls1.2 tls1.3');
  lines.push('    }');
  lines.push('');
  lines.push('    # Security Headers');
  lines.push(generateSecurityHeaders({}));
  lines.push('');
  lines.push('    # Reverse Proxy');
  lines.push(`    ${generateReverseProxy({ upstream })}`);
  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate reverse proxy configuration
 * @param {Object} options - Reverse proxy options
 * @param {string} options.upstream - Upstream server address
 * @param {Object} [options.headers] - Additional headers to add
 * @returns {string} Reverse proxy configuration
 */
export function generateReverseProxy(options = {}) {
  const { upstream, headers = {} } = options;

  const lines = [`reverse_proxy ${upstream}`];

  // Add header configurations if provided
  for (const [key, value] of Object.entries(headers)) {
    lines.push(`    header_up ${key} ${value}`);
  }

  return lines.join('\n');
}

/**
 * Generate security headers configuration
 * @param {Object} options - Security header options
 * @returns {string} Security headers configuration
 */
export function generateSecurityHeaders(options = {}) {
  const {
    frameOptions = 'DENY',
    contentTypeOptions = 'nosniff',
    xssProtection = '1; mode=block',
    referrerPolicy = 'strict-origin-when-cross-origin',
  } = options;

  const lines = [
    '    header {',
    `        X-Frame-Options "${frameOptions}"`,
    `        X-Content-Type-Options "${contentTypeOptions}"`,
    `        X-XSS-Protection "${xssProtection}"`,
    `        Referrer-Policy "${referrerPolicy}"`,
    '        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"',
    '        -Server',
    '    }',
  ];

  return lines.join('\n');
}

/**
 * Create a Caddy configuration manager
 * @returns {Object} Caddy config manager with methods
 */
export function createCaddyConfig() {
  const sites = [];

  return {
    /**
     * Add a site configuration
     * @param {Object} siteConfig - Site configuration
     */
    addSite(siteConfig) {
      sites.push(siteConfig);
    },

    /**
     * Generate complete Caddyfile
     * @param {Object} [globalOptions] - Global Caddy options
     * @returns {string} Complete Caddyfile
     */
    generate(globalOptions = {}) {
      if (sites.length === 0) {
        return generateCaddyfile(globalOptions);
      }

      const lines = [
        '# Caddyfile Configuration',
        '# Generated by TLC Caddy Config',
        '',
        '{',
      ];

      if (globalOptions.email) {
        lines.push(`    email ${globalOptions.email}`);
      }

      lines.push('}');
      lines.push('');

      for (const site of sites) {
        lines.push(`${site.domain} {`);
        lines.push('    tls {');
        lines.push('        protocols tls1.2 tls1.3');
        lines.push('    }');
        lines.push('');
        lines.push(generateSecurityHeaders(site.headers || {}));
        lines.push('');
        lines.push(`    ${generateReverseProxy({ upstream: site.upstream || 'localhost:3000' })}`);
        lines.push('}');
        lines.push('');
      }

      return lines.join('\n');
    },

    /**
     * Get all configured sites
     * @returns {Array} Array of site configurations
     */
    getSites() {
      return [...sites];
    },
  };
}
