/**
 * Database Configuration Generator
 * PostgreSQL and Redis configuration
 */

/**
 * Generate PostgreSQL configuration
 * @param {Object} options - PostgreSQL configuration options
 * @param {boolean} [options.ssl=false] - Enable SSL
 * @param {number} [options.maxConnections=100] - Maximum connections
 * @param {string} [options.sharedBuffers='256MB'] - Shared buffers size
 * @param {string} [options.workMem='4MB'] - Work memory size
 * @returns {string} PostgreSQL configuration
 */
export function generatePostgresConfig(options = {}) {
  const {
    ssl = false,
    maxConnections = 100,
    sharedBuffers = '256MB',
    workMem = '4MB',
    effectiveCacheSize = '1GB',
    maintenanceWorkMem = '64MB',
  } = options;

  const lines = [
    '# PostgreSQL Configuration',
    '# Generated by TLC Database Config',
    '',
    '# Connection Settings',
    `max_connections = ${maxConnections}`,
    '',
    '# Memory Settings',
    `shared_buffers = ${sharedBuffers}`,
    `work_mem = ${workMem}`,
    `effective_cache_size = ${effectiveCacheSize}`,
    `maintenance_work_mem = ${maintenanceWorkMem}`,
    '',
    '# SSL Configuration',
    `ssl = ${ssl ? 'on' : 'off'}`,
  ];

  if (ssl) {
    lines.push("ssl_cert_file = '/etc/ssl/certs/server.crt'");
    lines.push("ssl_key_file = '/etc/ssl/private/server.key'");
  }

  lines.push('');
  lines.push('# Logging');
  lines.push("log_destination = 'stderr'");
  lines.push('logging_collector = on');
  lines.push("log_directory = 'pg_log'");
  lines.push("log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'");
  lines.push('');
  lines.push('# Performance');
  lines.push('checkpoint_completion_target = 0.9');
  lines.push('wal_buffers = 16MB');
  lines.push('default_statistics_target = 100');

  return lines.join('\n');
}

/**
 * Generate pg_hba.conf configuration
 * @param {Object} options - pg_hba configuration options
 * @param {Array} options.rules - Authentication rules
 * @returns {string} pg_hba.conf configuration
 */
export function generatePgHba(options = {}) {
  const { rules = [] } = options;

  const lines = [
    '# PostgreSQL Client Authentication Configuration',
    '# Generated by TLC Database Config',
    '',
    '# TYPE  DATABASE        USER            ADDRESS                 METHOD',
    '',
    '# Local connections',
    'local   all             all                                     peer',
    'local   all             postgres                                peer',
    '',
    '# IPv4 local connections',
    'host    all             all             127.0.0.1/32            scram-sha-256',
    '',
    '# IPv6 local connections',
    'host    all             all             ::1/128                 scram-sha-256',
    '',
    '# Custom rules',
  ];

  for (const rule of rules) {
    const { type, database, user, address, method } = rule;
    lines.push(`${type}\t${database}\t\t${user}\t\t${address}\t\t${method}`);
  }

  return lines.join('\n');
}

/**
 * Generate Redis configuration
 * @param {Object} options - Redis configuration options
 * @param {string} [options.requirepass] - Password for authentication
 * @param {boolean} [options.tls=false] - Enable TLS
 * @param {number} [options.maxmemory] - Maximum memory in bytes
 * @param {string} [options.maxmemoryPolicy='allkeys-lru'] - Eviction policy
 * @returns {string} Redis configuration
 */
export function generateRedisConfig(options = {}) {
  const {
    requirepass,
    tls = false,
    maxmemory,
    maxmemoryPolicy = 'allkeys-lru',
    port = 6379,
    bind = '127.0.0.1',
  } = options;

  const lines = [
    '# Redis Configuration',
    '# Generated by TLC Database Config',
    '',
    '# Network',
    `bind ${bind}`,
    `port ${tls ? 0 : port}`,
    'protected-mode yes',
    '',
  ];

  if (tls) {
    lines.push('# TLS Configuration');
    lines.push(`tls-port ${port}`);
    lines.push('tls-cert-file /etc/redis/redis.crt');
    lines.push('tls-key-file /etc/redis/redis.key');
    lines.push('tls-ca-cert-file /etc/redis/ca.crt');
    lines.push('');
  }

  if (requirepass) {
    lines.push('# Security');
    lines.push(`requirepass ${requirepass}`);
    lines.push('');
  }

  lines.push('# Memory Management');
  if (maxmemory) {
    lines.push(`maxmemory ${maxmemory}`);
  }
  lines.push(`maxmemory-policy ${maxmemoryPolicy}`);
  lines.push('');

  lines.push('# Persistence');
  lines.push('appendonly yes');
  lines.push('appendfsync everysec');
  lines.push('');

  lines.push('# Logging');
  lines.push('loglevel notice');
  lines.push('logfile /var/log/redis/redis-server.log');

  return lines.join('\n');
}

/**
 * Create a database configuration manager
 * @returns {Object} Database config manager with methods
 */
export function createDatabaseConfig() {
  return {
    /**
     * Generate PostgreSQL configuration
     * @param {Object} options - PostgreSQL options
     * @returns {string} PostgreSQL configuration
     */
    generatePostgres(options = {}) {
      return generatePostgresConfig(options);
    },

    /**
     * Generate pg_hba.conf configuration
     * @param {Object} options - pg_hba options
     * @returns {string} pg_hba configuration
     */
    generatePgHba(options = {}) {
      return generatePgHba(options);
    },

    /**
     * Generate Redis configuration
     * @param {Object} options - Redis options
     * @returns {string} Redis configuration
     */
    generateRedis(options = {}) {
      return generateRedisConfig(options);
    },

    /**
     * Generate all database configurations
     * @param {Object} options - Configuration options
     * @returns {Object} All generated configurations
     */
    generateAll(options = {}) {
      return {
        postgres: generatePostgresConfig(options.postgres || {}),
        pgHba: generatePgHba(options.pgHba || {}),
        redis: generateRedisConfig(options.redis || {}),
      };
    },
  };
}
